// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
