// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms DEFAULT VALUES RETURNING id, created_at
`

func (q *Queries) CreateRoom(ctx context.Context) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom)
	var i Room
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms where id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, created_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
